name: BuildAndPushDockerImageToHarbor

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for tags
          
      - name: Harbor Login
        uses: docker/login-action@v3
        with:
          registry: harbor.gwdg.de
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Get Maven Project Version
        run: |
          cd qualitypatternmodel
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          BASE_VERSION=${POM_VERSION%.0}
          PATCH=$(git rev-list v$POM_VERSION..HEAD --count --first-parent)
          VERSION="$BASE_VERSION.$PATCH"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Harbor Build and Push
        uses: docker/build-push-action@v5
        with:
          context: qualitypatternmodel
          file: qualitypatternmodel/Dockerfile
          push: true
          tags: harbor.gwdg.de/aqinda/qpm:latest, harbor.gwdg.de/aqinda/qpm:${{ env.VERSION }}
